# Generated by Django 4.0.4 on 2022-05-03 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specs',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
